#!/bin/bash

_get_ziplink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "goodcat" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RhbWlsQm90cy9UYW1pbFVzZXJCb3Q=" | base64 -d
    elif [[ $UPSTREAM_REPO == "badcat" ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RhbWlsQm90cy9UYW1pbFVzZXJCb3Q=" | base64 -d
    fi
}


_run_python_code() {
    python3${pVer%.*} -c "$1"
}


_set_bot () {
    local zippath
    zippath="tamiluserbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_ziplink) -O "$zippath"
    echo "  Unpacking Data ..."
    CATPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    _run_catpack_git
    cd $CATPATH
    _run_cat_git
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    chmod -R 755 bin
    echo "    Starting TamilUserBot    "
    echo "
            ::::::::::::::::::::::::::::::::::::::::::::::::::::::: 
            :#########..#####...####.....####..#########..## .....: 
            :.. ##.....##....## ##..#...#..##......##.....## .....: 
            :.. ##.....##....## ##...#::#..##......##.....## .....: 
            :.. ##.....######## ##....#....##......##.....## .....: 
            :.. ##.....#.....## ##.........##......##.....## .....: 
            :.. ##.....#.....## ##.........##......##.....## .....: 
            :.. ##.....#.....## ##.........##..#########..#######.: 
            ::::::::::::::::::::::::::::::::::::::::::::::::::::::: 
    "

    echo "
     :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
     :##....##...######..######..########   #########....######..########:
     :##....##..##.......##......##.....##   ##.....##..##....##....##...:
     :##....##..##.......##......##.....##   ##.....##..##....##....##...:
     :##....##...#####...######..########    #########..##....##....##...:
     :##....##.......##..##......##...##     ##.....##..##....##....##...:
     :##....##.......##..##......##....##    ##.....##..##....##....##...:
     :.######...######...######..##....###..#########...#######.....##...:
     :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    "
    python3 -m userbot
}

_set_bot
